controller:
    deployment:
        image:
            repository: quay.io/pipelines-feedback/batchv1
            pullPolicy: Always

rbac:
    jobRules:
        - apiGroups: ["batch"]
          resources: ["jobs"]
          verbs: ["list", "get", "watch"]
