---
apiVersion: batch/v1
kind: Job
metadata:
    name: sleep
    namespace: default
    annotations:
        pipelinesfeedback.keskad.pl/https-repo-url: "https://github.com/keskad/jx-gitops"
        pipelinesfeedback.keskad.pl/commit: "76ea7c746d4e4ac42c44bf72946d3b0d399553dd"
        pipelinesfeedback.keskad.pl/ref: "refs/heads/test-pr"
        pipelinesfeedback.keskad.pl/pr-id: "2"
spec:
    template:
        spec:
            containers:
                - name: sleep
                  image: busybox:latest
                  command: ["/bin/sh", "-c", "sleep 10; wget https://example.org/ -O /dev/stdout; sleep 1"]
            restartPolicy: Never
    backoffLimit: 4
