---
apiVersion: batch/v1
kind: Job
metadata:
    name: sleep
    namespace: default
    annotations:
        pipelines-feedback.keskad.pl/https-repo-url: "https://github.com/keskad/jx-gitops"
        pipelines-feedback.keskad.pl/commit: "a78274796fb522f558c3e17ac2393c5a93b3fc6c"
        pipelines-feedback.keskad.pl/ref: "refs/heads/keskad-patch-1"
        pipelines-feedback.keskad.pl/pr-id: "1"
spec:
    template:
        spec:
            containers:
                - name: sleep
                  image: busybox:latest
                  command: ["/bin/sh", "-c", "sleep 10"]
            restartPolicy: Never
    backoffLimit: 4
