{{- if .Values.controller.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
    name: {{ include "app.controller.serviceAccountName" . }}
    labels:
        {{- include "app.labels" . | nindent 8 }}
  {{- with .Values.controller.serviceAccount.annotations }}
    annotations:
        {{- toYaml . | nindent 8 }}
  {{- end }}
{{- end }}
