---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
    name: {{ include "app.fullname" . }}-cr
    annotations:
        description: |
            Allows to list PFConfig across the cluster.
            Optionally allows to list all Jobs on the cluster when `.Values.rbac.bindToNamespaces` is not populated
    labels:
      {{- include "app.labels" . | nindent 6 }}
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: {{ include "app.fullname" . }}-cr
subjects:
    - kind: ServiceAccount
      name: {{ include "app.controller.serviceAccountName" . }}
      namespace: {{ .Release.Namespace }}
