apiVersion: v1
kind: ConfigMap
metadata:
    name: {{ include "app.fullname" . }}-default-config
    labels:
      {{- include "app.labels" . | nindent 6 }}
data:
    pipelines-feedback.json: |
        {{ toJson $.Values.controller.defaultConfig }}
