{{ range $num, $namespace := .Values.rbac.bindToNamespaces }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    name: {{ include "app.fullname" . }}-access
    namespace: {{ $namespace }}
    annotations:
        description: |
            Allows to reach PFConfig and Jobs in a namespace.
    labels:
      {{- include "app.labels" . | nindent 6 }}
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: {{ include "app.fullname" . }}-access
subjects:
    - kind: ServiceAccount
      name: {{ include "app.controller.serviceAccountName" . }}
      namespace: {{ $namespace }}
{{- end }}
