{{- if .Values.rbac.bindToNamespaces }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    name: {{ include "app.fullname" . }}-access
    annotations:
        description: |
            Allows to reach PFConfig and Jobs in a namespace.
    labels:
      {{- include "app.labels" . | nindent 6 }}
rules:
    - apiGroups: ["pipelinesfeedback.keskad.pl"]
      resources: ["pfconfigs"]
      verbs: ["list", "get"]

    {{ toYaml .Values.rbac.jobRules | nindent 4 }}
{{- end }}
