
{{ if .Values.rbac.bindToNamespaces }}
# Grant access only to specific namespaces
{{ range $num, $namespace := .Values.rbac.bindToNamespaces }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    name: {{ include "app.fullname" . }}
    namespace: {{ $namespace }}
    labels:
      {{- include "app.labels" . | nindent 6 }}
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: {{ include "app.fullname" . }}-secrets
subjects:
    - kind: ServiceAccount
      name: {{ include "app.controller.serviceAccountName" . }}
      namespace: {{ $namespace }}
{{ end }}
{{ else }}

# When 'bindToNamespaces' is not specified, then we assume access should be at the cluster scope
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
    name: {{ include "app.fullname" . }}
    labels:
      {{- include "app.labels" . | nindent 6 }}
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: {{ include "app.fullname" . }}
subjects:
    - kind: ServiceAccount
      name: {{ include "app.controller.serviceAccountName" . }}
      namespace: {{ .Release.Namespace }}
{{ end }}
