---
apiVersion: v1
kind: Service
metadata:
    name: {{ include "app.fullname" . }}
    labels:
        {{- include "app.labels" . | nindent 8 }}
spec:
    type: {{ .Values.controller.service.type }}
    ports:
        - port: {{ .Values.controller.service.port }}
          targetPort: http
          protocol: TCP
          name: http
    selector:
        {{- include "app.selectorLabels" . | nindent 8 }}
