/*
Copyright Damian Kęska.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	pipelinesfeedbackkeskadplv1alpha1 "github.com/Kubernetes-Native-CI-CD/pipelines-feedback-core/pkgs/apis/pipelinesfeedback.keskad.pl/v1alpha1"
	versioned "github.com/Kubernetes-Native-CI-CD/pipelines-feedback-core/pkgs/client/clientset/versioned"
	internalinterfaces "github.com/Kubernetes-Native-CI-CD/pipelines-feedback-core/pkgs/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/Kubernetes-Native-CI-CD/pipelines-feedback-core/pkgs/client/listers/pipelinesfeedback.keskad.pl/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// PFConfigInformer provides access to a shared informer and lister for
// PFConfigs.
type PFConfigInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.PFConfigLister
}

type pFConfigInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewPFConfigInformer constructs a new informer for PFConfig type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewPFConfigInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredPFConfigInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredPFConfigInformer constructs a new informer for PFConfig type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredPFConfigInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.PipelinesfeedbackV1alpha1().PFConfigs(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.PipelinesfeedbackV1alpha1().PFConfigs(namespace).Watch(context.TODO(), options)
			},
		},
		&pipelinesfeedbackkeskadplv1alpha1.PFConfig{},
		resyncPeriod,
		indexers,
	)
}

func (f *pFConfigInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredPFConfigInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *pFConfigInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&pipelinesfeedbackkeskadplv1alpha1.PFConfig{}, f.defaultInformer)
}

func (f *pFConfigInformer) Lister() v1alpha1.PFConfigLister {
	return v1alpha1.NewPFConfigLister(f.Informer().GetIndexer())
}
