name: Build & Test & Make snapshot
on:
    push:
        branches:
            - main
    pull_request:

jobs:
    build:
        uses: kube-cicd/.github/.github/workflows/app.common.yaml@main
        secrets:
            containerRegistryUsername: "${{ secrets.QUAY_USERNAME }}"
            containerRegistryPassword: "${{ secrets.QUAY_PASSWORD }}"
        with:
            containerImage: "quay.io/pipelines-feedback/batchv1"
            containerRegistryHost: "quay.io"
            goVersion: "1.25"

    release-helm:
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: kube-cicd/.github/.github/workflows/helm.common.yaml@main
        needs: [ "build" ]
        secrets:
            registryUsername: "${{ secrets.QUAY_USERNAME }}"
            registryPassword: "${{ secrets.QUAY_PASSWORD }}"
        with:
            chartRepoName: "pipelines-feedback"
            chartName: "batchv1-chart"
            chartPath: "charts/batchv1-chart"
            enableHelmDocs: false
            registryHost: "quay.io"
